### PR TITLE
KA -Update fixtures for recommendation requests based on changes in entity file

### PR DESCRIPTION
**Pull request by kanav9063**
Description

- Added professorId, neededByDate to oneRecommendationRequest and threeRecommendationRequests to update the fixtures based on updated entity files 

Testing

- No tests needed

Closes https://github.com/ucsb-cs156-f24/proj-rec-f24-07/issues/55

### CODE REVIEW

**Review by Ponmo — APPROVED** [review]
These changes look good, just delete the old code to fix the merge conflict.

**Review by Ponmo — DISMISSED** [review]
LGTM! These changes accurately reflect the new entity. Just prettier some files

**Review by Ponmo — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
