### PR TITLE
nw-remove-diningcommons

### LINKED ISSUE #26: BACKEND: Remove UCSBDiningCommons Backend

### PR DESCRIPTION
**Pull request by Ponmo**
#### Description:
- Removed all frontend, backend, DB, and tests that relied on dining commons.
- Changed Swagger integration tests to validate on general Swagger text instead of dining commons

#### Tests:
- Passed all unit, integration, and mutation tests.

#### Related Issue:
- Closes #26

### CODE REVIEW

**Comment by pconrad** [comment]
Nice... it appears that you understand why the one integration test is failing.

If you want, you could rewrite it into an integration test that checks whether `System Information` appears on the Swagger UI page.  The main intent of this integration test is just to "send up a flag" if Swagger suddenly stops working, so you use use `System Information` since that's unlikely to go away (unlike Restaurants and UCSBDates) and is already in the app.

That would allow you to get this merged more quickly.  Just a suggestion!

**Comment by Ponmo** [comment]
Rebased and changed the integration tests for swagger to a more general case as they are only meant as a health check (as recommended).

**Review by Ramon-W — APPROVED** [review]
The modified test is a bit more generic now but it's responsibility is to just check whether swagger page loads or not so it looks good to me.

Thanks!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
